server:
  port: 9000

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: test-id
      auto-offset-reset: earliest
